### ISSUE TITLE
Create examples

### ISSUE THREAD

**Issue by chambodn** [SkySoft-ATM/gorillaz#1]
Despite the fact that this framework seems promising, we are suffering from lack of examples.
Would it be possible, with each release to provide examples on how to initialize (i.e. gaz.Init() changed with the new version and is now expected a map[string]interface{})

**Comment by teivah** [comment]
No need to create examples imho if we use the generators (project generation + code generation).
However, I've added in the main.go generated a way to initialize gorillaz.
